# Numpy Basics <hr style = "border:2.5px solid #126782"></hr>

<b>Mary Kris M. Mahandog</b>
<br>Computer Engineer

In [8]:
#%%pip install numpy --upgrade
#%pip install scipy --upgrade

In [9]:
#%pip install --upgrade pip

In [11]:
#imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [12]:
# 1-dimensional array
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [14]:
# size of an array
np.shape(array_a)

(3,)

In [15]:
# 1-dimensional array 
array_b = np.array([4,5,6])
array_b

array([4, 5, 6])

# 2D Array

In [16]:
# 2-dimensional array
my_array = np.array([[1,2,3],
                     [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# size of matrix 
np.shape(my_array)

(2, 3)

In [18]:
# transpose of a matrix
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
# size of matrix
np.shape(t_array)

(3, 2)

# Measures of Central Tedency

In [ ]:
# Jaguar vs Panther 
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [27]:
np.shape(resistance)

(2, 11)

In [28]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [29]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [31]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [33]:
# Mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [36]:
jag_mean = np.nanmean(resistance, axis=1)[0]
pan_mean = np.nanmean(resistance, axis=1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} ohms')
print(f'Panther_mean = {pan_mean:.2f} ohms')

Jaguar_mean = 9.40 ohms
Panther_mean = 10.75 ohms


In [37]:
# Median
np.nanmedian(resistance, axis=1)

array([9.8 , 9.55])

In [40]:
jag_median = np.nanmedian(resistance, axis=1)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]

print(f'Jaguar_median = {jag_median:.2f} ohms') 
print(f'Panther_median = {pan_median:.2f} ohms')

Jaguar_median = 9.80 ohms
Panther_median = 9.55 ohms


In [43]:
# Mode
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [44]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [45]:
jag_res = resistance[0]

print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode:
9.8 ohms
10.4 ohms


In [46]:
pan_res = resistance[1]


print ("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode:
9.1 ohms


# Measures of variability

In [47]:
# Jaguar vs Panther 
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [48]:
# Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [49]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [50]:
# 1st Quartile 
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [51]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [52]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [54]:
# IQR
print(f'Jaguar_IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther_IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar_IQR = 1.05 ohms
Panther_IQR = 1.50 ohms


In [56]:
# Variance 
res_var = np.nanvar(resistance, axis=1)
res_var

array([4.41818182, 9.9745    ])

In [57]:
print(f'Jaguar_IQR = {res_var[0]:.2f} ohms')
print(f'Panther_IQR = {res_var[1]:.2f} ohms')

Jaguar_IQR = 4.42 ohms
Panther_IQR = 9.97 ohms


In [58]:
# Standard Deviation
res_std = np.nanstd(resistance, axis=1)
res_std

array([2.10194715, 3.15824318])

In [59]:
print(f'Jaguar_Standard = {res_std[0]:.2f} ohms')
print(f'Panther_Standard = {res_std[1]:.2f} ohms')

Jaguar_Standard = 2.10 ohms
Panther_Standard = 3.16 ohms
